- hosts: localhost

  tasks:
  # - name: Install collection azure.azcollection
  #   community.general.ansible_galaxy_install:
  #     type: collection
  #     name: azure.azcollection

  # - name: Install Azure Requirements using pip
  #   ansible.builtin.pip:
  #     requirements: ~/.ansible/collections/ansible_collections/azure/azcollection/requirements-azure.txt

  - name: Create a resource group
    azure.azcollection.azure_rm_resourcegroup:
      name: ansible
      location: centralus
