---

collections:
  # - name: ansible.posix
  #   version: '>=1.3.0'
  - name: ansible.utils
    version: '>=4.1.0'
  # - name: community.crypto
  #   version: '>=2.2.2'
  - name: community.general
    version: '>=9.2.0'
  # - name: community.libvirt
  #   version: '>=1.0.2'
  # - name: community.okd
  #   version: '>=2.1.0'
  # - name: kubernetes.core
  #   version: '>=2.2.3'
  - name: azure.azcollection
    version: '>=2.6.0'