- name: Deploy a vNet in Azure
  hosts: localhost
  tasks:
    - name: Install Azure Requirements using pip
      ansible.builtin.pip:
        requirements: ~/.ansible/collections/ansible_collections/azure/azcollection/requirements.txt

    - name: Create a resource group
      azure.azcollection.azure_rm_resourcegroup:
        name: ansible
        location: eastus

    - name: Create a virtual network
      azure.azcollection.azure_rm_virtualnetwork:
        resource_group: ansible
        name: vnet
        address_prefixes: "10.0.0.0/24"
        location: eastus
