name: CI

on:
  push:
    branches: [ '**' ]
  pull_request:
    branches: [ '**' ]
  workflow_dispatch:
  schedule:
    - cron: '0 0 1 * *' # Run at midnight on the first of every month

jobs:
  # lint:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: check out the repository
  #       uses: actions/checkout@v4

  #     - name: lint Ansible Playbook
  #       uses: ansible/ansible-lint@v24
  #       with:
  #         args: playbooks/ # no flags. targeting the 'playbooks/' directory https://ansible.readthedocs.io/projects/lint/usage/#using-commands
  #         requirements_file: requirements.yml

  deploy:
    environment: Azure
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repository
        uses: actions/checkout@v4

      - name: Instantiate Ansible 'hosts' file
        run: sudo install -D inventories/hosts /etc/ansible/hosts

      # NOTE: We install azure.azcollection during this step. azure.azcollection is needed both to lint and to run the playbook. SHould I move installation to be its own step?
      # - name: lint Ansible Playbook
      #   uses: ansible/ansible-lint@v24
      #   with:
      #     args: playbooks/ # no flags. targeting the 'playbooks/' directory https://ansible.readthedocs.io/projects/lint/usage/#using-commands
      #     requirements_file: requirements.yml

      - name: install
        run: ansible-galaxy install -r requirements.yml --force

      - name: Run Ansible playbook
        run: ansible-playbook playbooks/azure.vnet.yml
        env:
          AZURE_CLIENT_ID: ${{ secrets.CLIENT_ID }}
          AZURE_SECRET: ${{ secrets.CLIENT_SECRET }}
          AZURE_SUBSCRIPTION_ID: ${{ secrets.SUBSCRIPTION_ID }}
          AZURE_TENANT: ${{ secrets.TENANT_ID }}

