name: CI

on:
  push:
    branches: [ '**' ]
  pull_request:
    branches: [ '**' ]
  workflow_dispatch:
  schedule:
    - cron: '0 0 1 * *' # Run at midnight on the first of every month

jobs:
  deploy:
    environment: Azure
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repository
        uses: actions/checkout@v4

      - name: Instantiate Ansible 'hosts' file
        run: sudo install -D inventories/hosts /etc/ansible/hosts

      - name: Install 'azure.azcollection'
        run: ansible-galaxy collection install azure.azcollection --force

      - name: lint Ansible Playbook
        uses: ansible/ansible-lint@v24
        with:
          args: playbooks/ # no flags. targeting the 'playbooks/' directory https://ansible.readthedocs.io/projects/lint/usage/#using-commands

      - name: Run Ansible playbook
        run: ansible-playbook playbooks/azure.vnet.yml
        env:
          AZURE_CLIENT_ID: ${{ secrets.CLIENT_ID }}
          AZURE_SECRET: ${{ secrets.CLIENT_SECRET }}
          AZURE_SUBSCRIPTION_ID: ${{ secrets.SUBSCRIPTION_ID }}
          AZURE_TENANT: ${{ secrets.TENANT_ID }}

