name: CI

on:
  push:
    branches: [ '**' ]
  pull_request:
    branches: [ '**' ]

  workflow_dispatch:

jobs:
  lint:
    # if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    steps:
      - name: Ensure Ansible is installed
        run: ansible --version

      - name: Check installed Collections
        run: ansible-galaxy collection list

      - name: list azure.azcollection
        run: ansible-galaxy collection list azure.azcollection

      - name: check out the repository
        uses: actions/checkout@v4

      - name: lint Ansible Playbook
        uses: ansible/ansible-lint@v24
        with:
          working_directory: "."
          args: "--exclude .github/"

  deploy:
    environment: Azure
    runs-on: ubuntu-latest
    steps:
      - name: Ensure Ansible is installed
        run: ansible --version

      - name: Check out the repository
        uses: actions/checkout@v4

      - name: Instantiate Ansible 'hosts' file
        run: sudo install -D hosts /etc/ansible/hosts

      - name: Run Ansible playbook
        run: ansible-playbook main.yml
        env:
          AZURE_CLIENT_ID: ${{ secrets.CLIENT_ID }}
          AZURE_SECRET: ${{ secrets.CLIENT_SECRET }}
          AZURE_SUBSCRIPTION_ID: ${{ secrets.SUBSCRIPTION_ID }}
          AZURE_TENANT: ${{ secrets.TENANT_ID }}

